spring:
  config:
    activate:
      on-profile: dev

application:
  name: dev-profile

logging:
  level.: DEBUG

gateway:
  urls:
    vacina-certa-command: ${VACCINA_CERTA_COMMAND}
    vacina-certa-query: ${VACCINA_CERTA_QUERY}